/* Verified external sources (fetched 8 Oct 2026). Topic files cite these by position with [text][n]. */
module.exports = {
  form26: { title: 'Income Tax Department: Form No. 26 FAQs (tax audit under section 63, Income-tax Act, 2025)', url: 'https://www.incometaxindia.gov.in/documents/d/guest/form-26-faqs' },
  form168: { title: 'Income Tax Department: Form No. 168 (Annual Information Statement) FAQs', url: 'https://www.incometaxindia.gov.in/documents/d/guest/form-168-faqs' },
  itAct: { title: 'PIB: Income-tax Act, 2025 comes into force from 1 April 2026', url: 'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2248005' },
  tgAudit: { title: 'TaxGuru: AY 2026-27 tax audit — Forms 3CA, 3CB and 3CD still apply; Form 26 starts later', url: 'https://taxguru.in/income-tax/ay-2026-27-tax-audit-forms-3ca-3cb-3cd-apply-form-26-starts.html' },
  s74A: { title: 'CBIC: Section 74A, CGST Act, 2017', url: 'https://taxinformation.cbic.gov.in/content/html/tax_repository/gst/acts/2017_CGST_act/active/chapter15/Section74A_v1.00.html' },
  rule99: { title: 'CBIC: Rule 99, CGST Rules, 2017 (scrutiny of returns, ASMT-10/11/12)', url: 'https://taxinformation.cbic.gov.in/content/html/tax_repository/gst/rules/cgst_rules/active/chapter11/rule99_v1.00.html' },
  dpdpRules: { title: 'PIB: Government notifies DPDP Rules (14 November 2025)', url: 'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2190014' },
  dpdpExplainer: { title: 'PIB: DPDP Rules, 2025 explainer (penalties under the DPDP Act, 2023)', url: 'https://static.pib.gov.in/WriteReadData/specificdocs/documents/2025/nov/doc20251117695301.pdf' },
  dpdpAct: { title: 'Digital Personal Data Protection Act, 2023 (Gazette text, MeitY)', url: 'https://www.meity.gov.in/static/uploads/2024/06/2bf1f0e9f04e6fb4f8fef35e82c42aa5.pdf' },
  icaiFees: { title: 'ICAI: FAQs on the Chartered Accountants Act — Clause (10), Part I, First Schedule and Regulation 192 (fees)', url: 'https://icai.org/post/5645' },
  trFop: { title: 'Thomson Reuters: 2025 Future of Professionals report (press release)', url: 'https://www.prnewswire.com/news-releases/the-ai-adoption-reality-check-firms-with-ai-strategies-are-twice-as-likely-to-see-ai-driven-revenue-growth-those-without-risk-falling-behind-302490973.html' },
  wtiIndia: { title: 'Microsoft: India findings of the 2025 Work Trend Index', url: 'https://news.microsoft.com/source/asia/2025/08/20/indias-workforce-goes-ai-first-as-frontier-firms-lead-the-transformation-microsoft-work-trend-index-2025/' },
  sa210: { title: 'ICAI AASB: Illustrative engagement letters under the Companies Act, 2013 (SA 210, Appendix 1)', url: 'https://www.icai.org/post/aasb-illustrative-audit-engagement-letter-under-companies-act-2013-17-12-2014' },
  nset: { title: 'ICAI Board of Studies: FAQs on the New Scheme of Education and Training', url: 'https://resource.cdn.icai.org/75315bos-faqs-nset-july1.pdf' },
  ais2026: { title: 'ICAI: AI Innovation Summit 2026 press release (26 June 2026)', url: 'https://www.icai.org/post/icai-ais2026-26062026' },
  caGpt: { title: 'ICAI: CA GPT platform press release (25 November 2024)', url: 'https://icai.org/post/prc-icai-unveils-groundbreaking-ca-gpt-platform' },
  siaComp: { title: 'ICAI Internal Audit Standards Board: Compendium of Standards on Internal Audit, 2026 (SIA 240, Use of Tools)', url: 'https://internalaudit.icai.org/wp-content/uploads/2026/03/Comp-of-Stnd-on-Internal-Audit-26.pdf' },
  caroPib: { title: 'PIB: Notification of Companies (Auditor’s Report) Order, 2020', url: 'https://www.pib.gov.in/newsite/PrintRelease.aspx?relid=199571' },
  caroText: { title: 'Companies (Auditor’s Report) Order, 2020 — full text (TaxGuru)', url: 'https://taxguru.in/company-law/caro-2020.html' },
  gartner: { title: 'Gartner: Finance AI adoption remains steady in 2025 (press release)', url: 'https://www.gartner.com/en/newsroom/press-releases/2025-11-18-gartner-survey-shows-finance-ai-adoption-remains-steady-in-2025' },
  companiesAct: { title: 'Companies Act, 2013 — Gazette text (PRS Legislative Research)', url: 'https://prsindia.org/files/bills_acts/acts_parliament/2013/companies-act%2C-2013.pdf' },
  sebiFaq: { title: 'SEBI: FAQs on the LODR Regulations (Regulation 33 financial results)', url: 'https://www.sebi.gov.in/sebi_data/faqfiles/apr-2025/1745399101865.pdf' },
  sahamati: { title: 'Sahamati: Account Aggregator crosses 500 million consents (2 September 2026)', url: 'https://sahamati.org.in/media-article/account-aggregator-crosses-500-million-consents-as-india-marks-5th-aa-foundation-day/' },
  indAsRules: { title: 'Companies (Indian Accounting Standards) Rules, 2015 (Gazette text)', url: 'https://thc.nic.in/Central%20Governmental%20Rules/Companies%20(Indian%20Accounting%20Standards)%20Rules,2015.pdf' },
  msmed: { title: 'Micro, Small and Medium Enterprises Development Act, 2006 (Gazette text, DC-MSME)', url: 'https://www.dcmsme.gov.in/msmed2006.pdf' },
  msmeBudget: { title: 'PIB: MSME investment and turnover limits enhanced 2.5 and 2 times (Union Budget 2025-26)', url: 'https://pib.gov.in/Pressreleaseshare.aspx?PRID=2098389' }
};
